title: Corn Disease Detector (CDD)
email: ai2021grupo7[at]gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Early plant disease detector model built using neural networks. Saturdays AI Quito 2021.
  
github_username:  corndiseasedetector

theme: jekyll-theme-modernist
